Improved creation of sportfields
OlympGuide/Frontend pull request #20
Opened 2024-04-22 06:42 UTC by jasminstofer

**Sportfield creation:** 
- Sportfield kann mittels Pin / Marker auf der Karte direkt gesetzt werden
- Sportfield kann durch das eingeben der Adresse erstellt werden, es gibt Adressvervollständigung
- Eigentümer können die Inhaberschaft eines Sportfields beim Erstellen beantragen

**Weiteres:**
- Demostore für Demo, kann mittels Button in 'Einstellungen' getriggered werden
- Vorbereitungen für das Schicken von Files (Inhaberschaft) -> diese wurden auskommentiert, da das Backend noch keine Files akzeptiert.

2024-04-26 06:34 UTC, aubrydario requested changes

2024-04-26 06:34 UTC, aubrydario commented on src/components/AddressCompletion.vue
> +const selectAddress = (address: any) => {
typ any?

2024-04-26 06:34 UTC, aubrydario commented on src/types/Map.ts
> +export type ShowSportField = Omit<SportField, 'file'>;
Ist der type ShowSportField nötig? file ist ja optional.

2024-04-26 06:34 UTC, aubrydario commented on src/layouts/SidebarLayout.vue
> +    visible: true,
Brauchts das visible? es gibt ja schon die hide option

2024-04-26 06:34 UTC, aubrydario commented on src/api/sportFieldProposalApi.ts
>    return api.post(PROPOSAL_PATH, data);
Ich kann kein Sportplatz erstellen wenn ich auf die Karte klicke und keine Adresse eingebe. Error: (The SportFieldAddress field is required.)

2024-04-26 08:07 UTC, jasminstofer commented on src/api/sportFieldProposalApi.ts
>    return api.post(PROPOSAL_PATH, data);
Das wird durch die Anpassungen im Backend gelöst, habe ich getetstet mit Ilimeas Branch

2024-04-26 08:12 UTC, jasminstofer commented on src/components/AddressCompletion.vue
> +const selectAddress = (address: any) => {
stimmt, habe es angepasst

2024-04-26 08:18 UTC, jasminstofer commented on src/layouts/SidebarLayout.vue
> +    visible: true,
Ich glaube schon, da die beiden auf verschiedenen Ebenen im <template> gebraucht werden. Bei mir hat das nicht funktioniert, wenn ich hide für beides benutzt habe

2024-04-28 18:06 UTC, aubrydario approved these changes

2024-04-28 18:06 UTC, merged